name: Generate snake animation

on:
  schedule:
    - cron: "0 17 * * *" # Jalan setiap jam 12 malam WIB
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Ensure assets directory exists
        run: mkdir -p assets

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: assets/snake.svg?palette=github-dark

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/snake.svg
          git commit -m "Update snake.svg" || exit 0
          git push origin main
